server:
    host: 0.0.0.0
    port: 8080
    context-path: '/mm'
logging:
    level:
        console: DEBUG
        file: INFO
    filename: 'tmp/moneymitra_logs.log'
    format: '%(asctime)s > %(levelname)s [%(name)s] --- %(message)s'
    max_file_size: 10485760  # 10 MB
    backup_count: 5

app:
    application-name: Money Mitra Services
    profiles:
        active: dev
    datasource:
        dev:
            database1-db:
                conn_string: "${DATABASE1_URL}"
                driver-name: "${DB1_DRIVER_NAME}"
                host: "${DB1_HOST}"
                port: "${DB1_PORT}"
                username: "${DB1_USER}"
                database-name: "${DB1_NAME}"
                password: "${DB1_PASSWORD}"
            database2-db:
                conn_string: "${DATABASE2_URL}"
                driver-name: "${DB2_DRIVER_NAME}"
                host: "${DB2_HOST}"
                port: "${DB2_PORT}"
                username: "${DB2_USER}"
                database-name: "${DB2_NAME}"
                password: "${DB2_PASSWORD}"
        staging:
            database1-db:
                conn_string: "postgresql://postgres:postgres123@localhost:5432/moneymitra1"
                driver-name: postgresql
                host: localhost
                port: 5432
                username: postgres
                database-name: moneymitra1
                password: postgres123
            database2-db:
                conn_string: "postgresql://postgres:postgres123@localhost:5432/moneymitra2"
                driver-name: postgresql
                host: localhost
                port: 5432
                username: postgres
                database-name: moneymitra2
                password: postgres123

