"""Adding portfolio Table

Revision ID: c13e4d9a8474
Revises: 
Create Date: 2024-08-11 19:27:52.573472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13e4d9a8474'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_data_advisory',
    sa.Column('pf_seqid', sa.BIGINT(), nullable=False),
    sa.Column('investor_account_id', sa.String(), nullable=True),
    sa.Column('pf_tntid', sa.String(), nullable=True),
    sa.Column('pf_orgid', sa.String(), nullable=True),
    sa.Column('pf_advid', sa.String(), nullable=True),
    sa.Column('pf_name', sa.String(), nullable=True),
    sa.Column('pf_description', sa.String(), nullable=True),
    sa.Column('pf_ticker', sa.String(), nullable=True),
    sa.Column('pf_weight', sa.FLOAT(), nullable=True),
    sa.Column('pf_price', sa.FLOAT(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('modified_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('pf_seqid'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_data_advisory', schema='public')
    # ### end Alembic commands ###
