"""removing columns

Revision ID: de74783a8900
Revises: c13e4d9a8474
Create Date: 2024-08-11 19:39:40.750047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de74783a8900'
down_revision: Union[str, None] = 'c13e4d9a8474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_data_advisory', 'pf_tntid')
    op.drop_column('portfolio_data_advisory', 'pf_orgid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_data_advisory', sa.Column('pf_orgid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('portfolio_data_advisory', sa.Column('pf_tntid', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
